Make markers be drawed above planets
coolStory24/physics_rocket-launch-simulation pull request #25
Opened 2024-09-20 17:56 UTC by iv4n-t3a

2024-09-20 18:01 UTC, anishchenkoivan requested changes

2024-09-20 18:01 UTC, anishchenkoivan commented on simulator/simobjects.py
> +            SimObject.draw_text_marker(self, screen, scale, offset, font, self.entity.radius * scale)
не так надо

2024-09-21 18:23 UTC, iv4n-t3a commented
В последнем комите проблема не в том, что я не могу написать `super()`, а в том, что публичный `draw_text_marker` не должен принимать смещение вверх относительно объекта. Поэтому я вынес отдельный protected метод

2024-09-22 09:42 UTC, anishchenkoivan approved these changes

2024-09-22 10:14 UTC, merged