Feature/inner solar system
coolStory24/physics_rocket-launch-simulation pull request #41
Opened 2024-09-29 17:40 UTC by anishchenkoivan

Add basic solar system

2024-09-29 17:49 UTC, iv4n-t3a reviewed
Почему они начинают с одной прямой, сделай или рандомный полярный угол, или реальные данные

2024-09-29 18:00 UTC, iv4n-t3a requested changes
комент выше

2024-09-29 18:47 UTC, anishchenkoivan commented
Меркурий и Венера нам не нужны

2024-09-29 18:48 UTC, anishchenkoivan commented
Предлагаю сделать реальные углы, когда добавится возможность сохранять/удалять конфигурацию из json, если мы хотим просто алгоритм проверить, то все положения считать нецелессобразно

2024-09-30 07:18 UTC, iv4n-t3a approved these changes

2024-09-30 12:56 UTC, merged